name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn build-and-test
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
